# To change the coverage (or any other set variable in the central Makefile) the include statement must occur after the overwritten variable, like this:
# fail verify:coverage job if branch coverage is below a specific value.
# default value: 100
# COV_FAIL_UNDER=99

include python3-makefile/Makefile

include tests/Makefile
